### ISSUE TITLE
#1 Basic Structure and Navigation

### ISSUE THREAD

**Issue by SophiaLinetti** [SophiaZett/Cottage-App#1]
## Titel

Basic Structure and Navigation

## Value Proposition

As a user
I want to easily navigate through the app
so that I can quickly access different pages

## Description

<img width="881" alt="Bildschirmfoto 2024-03-26 um 15 48 03" src="https://github.com/SophiaZett/Ferienhaus-Meergefuehl/assets/151823139/308a1ba2-cd6c-499e-a80d-bbf1823033d7">

## Acceptance criteria

- [ ] The app has a homepage and separate pages for contact, guest talk, feedback and recommendations
- [ ] Users can navigate to the other pages from the homepage
- [ ] The navigation is intuitive and smooth, especially on mobile devices

## Tasks

- [ ] Set up the Next.js project
- [ ] Create the file structure for pages (pages/index.jsx, pages/contact.jsx, pages/cottage-talk.jsx, pages/recommendations.jsx, pages/feedback.jsx)
- [ ] Implement routing between the pages.
