### ISSUE TITLE
#2 Landing Page - Basic Layout

### ISSUE THREAD

**Issue by SophiaLinetti** [SophiaZett/Cottage-App#2]
## Titel

Landing Page - Basic Layout

## Value Proposition

As a user
I want an appealing overview on the homepage
so that I can get a first impression of the contents offered.

## Description

<img width="493" alt="Bildschirmfoto 2024-03-26 um 16 45 49" src="https://github.com/SophiaZett/Ferienhaus-Meergefuehl/assets/151823139/d3408853-1478-457f-9073-c4a1ac652fa3">

## Acceptance criteria

- [ ] An inviting picture of the vacation house is displayed on the homepage
- [ ] There are preview areas for the pages with feedback, guest talk, and recommendations
- [ ] The preview areas contain short descriptions or titles that pique interest for more.

## Tasks

- [ ] Design the basic layout with Styled Components
- [ ] Incorporate an appealing picture of the vacation house
- [ ] Create preview components for the main features of the app
